# Generated by Django 3.0.8 on 2020-07-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200716_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='C:\\Users\\Generic\\Desktop\\Comp Sci\\Fullstack\\shopping_cart\\shopping_cart\\media/images/placeholder.png', null=True, upload_to='images/'),
        ),
    ]
