# Generated by Django 3.0.8 on 2020-07-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200716_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='C:\\Users\\Generic\\Desktop\\Comp Sci\\Fullstack\\shopping_cart\\shopping_cart\\media/images/placeholder.png', upload_to='images/'),
        ),
    ]
